# -*- coding: utf-8 -*-
"""SPRINT 4 - Caio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15UWV2r3zVzc37DNc3EwwMivJQVUfkpiI

Sprint 4 - Caios
Fábrica de projetos Ágeis

Grupo constituido por;
- João Gabriel Pieraço Silva
- Luis Felipe Botelho
- João Pedro Deo
"""

i = 0
users = []
senhas = []

while(True):
    print("Bem vindo ao Projeto Carbono Zero.")
    print("Por gentileza, selecione uma das opções abaixo:")
    print("1 - Cadastro")
    print("2 - Login")
    print("3 - Sair")
    print("============================================================")
    print(" ")
    
    opcao = input("Digite a opção 1, 2 ou 3: ")
    
    if opcao == "1":
        qtd_usuarios = int(input("Quantos usuários serão cadastrados? "))

        while i < qtd_usuarios:
            user = input("Informe o seu usuário: ")
            users.append(user)
            senha = input("Informe o seu usuário: ")
            senhas.append(senha)
            i += 1
    print("Obrigado!")
    print("Seu login foi cadastrado com sucesso.")
    print(" ")
    print("========================================================")
    print(" ")
    if opcao == "2":
        login_user = input("Digite seu usuário: ")
        login_senha = input("Digite sua senha: ")
        logado = False
        print(" ")
        for user in users:
            if user == login_user:
                if login_senha == senhas[users.index(user)]:
                    logado = True
                    print("Login efetuado com sucesso")
                    print(" ")
                    print(" ")
                    print("========================================================")
                    print("========================================================")
                    print(" ")
        if logado == False:
            print("Dados inválidos")
            print(" ")
            print("========================================================")
            print("========================================================")
            print(" ")
    if opcao == "3":
        break
        print("Até breve!")